version: '2'

services:
  ruby:
    image: abakpress/ruby-app:2.3-latest
    env_file:
      - .env
      - ../.env.${RAILS_ENV}
    command: bash

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=twinkle

  redis:
    image: redis:3-alpine
